//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4961
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace S3GBusEntity {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SPNames_SQL_ORA {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SPNames_SQL_ORA() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("S3GBusEntity.SPNames_SQL_ORA", typeof(SPNames_SQL_ORA).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S3G_SA_Del_CmpLstValues.
        /// </summary>
        public static string S3G_Delete_Bank_Listvalues {
            get {
                return ResourceManager.GetString("S3G_Delete_Bank_Listvalues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S3G_SA_Del_CmpDet.
        /// </summary>
        public static string S3G_Delete_Company_Details {
            get {
                return ResourceManager.GetString("S3G_Delete_Company_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S3G_SA_Del_CustAlert.
        /// </summary>
        public static string S3G_Delete_CustomerAlert {
            get {
                return ResourceManager.GetString("S3G_Delete_CustomerAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S3G_SA_Del_DNCDet.
        /// </summary>
        public static string S3G_Delete_DNCDetails {
            get {
                return ResourceManager.GetString("S3G_Delete_DNCDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S3G_SA_Del_EsclnDet.
        /// </summary>
        public static string S3G_Delete_EscalationDetails {
            get {
                return ResourceManager.GetString("S3G_Delete_EscalationDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S3G_SA_Del_ProdDet.
        /// </summary>
        public static string S3G_Delete_Product_Details {
            get {
                return ResourceManager.GetString("S3G_Delete_Product_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S3G_SA_Del_RoleCodeMastDet.
        /// </summary>
        public static string S3G_Delete_RoleCodeMaster_Details {
            get {
                return ResourceManager.GetString("S3G_Delete_RoleCodeMaster_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S3G_SA_Del_UTPAPgmAccsDet.
        /// </summary>
        public static string S3G_Delete_UTPAProgramAccess_Details {
            get {
                return ResourceManager.GetString("S3G_Delete_UTPAProgramAccess_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S3G_SA_Get_AccSetupDetPagi.
        /// </summary>
        public static string S3G_Get__Account_Setup_Details_Paging {
            get {
                return ResourceManager.GetString("S3G_Get__Account_Setup_Details_Paging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S3G_SA_Get_AccCodeDet.
        /// </summary>
        public static string S3G_Get_Account_Code_Details {
            get {
                return ResourceManager.GetString("S3G_Get_Account_Code_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S3G_SA_Get_AccSetupDet.
        /// </summary>
        public static string S3G_Get_Account_Setup_Details {
            get {
                return ResourceManager.GetString("S3G_Get_Account_Setup_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S3G_SA_Get_AstDetEnqUpd.
        /// </summary>
        public static string S3G_Get_Asset_Details_Enquiry_Updation {
            get {
                return ResourceManager.GetString("S3G_Get_Asset_Details_Enquiry_Updation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S3G_SA_Get_BnkLOBLst.
        /// </summary>
        public static string S3G_Get_Bank_LOBList {
            get {
                return ResourceManager.GetString("S3G_Get_Bank_LOBList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S3G_SA_Get_BnkStmtID.
        /// </summary>
        public static string S3G_Get_Bank_Statement_ID {
            get {
                return ResourceManager.GetString("S3G_Get_Bank_Statement_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S3G_SA_Get_BnkStmtLOVDet.
        /// </summary>
        public static string S3G_Get_Bank_Statement_LOVDetails {
            get {
                return ResourceManager.GetString("S3G_Get_Bank_Statement_LOVDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S3G_SA_Get_BnkStmtDataCaptDet.
        /// </summary>
        public static string S3G_Get_Bank_Stmt_Data_CaptureDetails {
            get {
                return ResourceManager.GetString("S3G_Get_Bank_Stmt_Data_CaptureDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S3G_SA_Get_BnkStmtLOVDet.
        /// </summary>
        public static string S3G_Get_Bank_Stmt_LOVDetails {
            get {
                return ResourceManager.GetString("S3G_Get_Bank_Stmt_LOVDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S3G_SA_Get_BrnDet.
        /// </summary>
        public static string S3G_Get_Branch_Details {
            get {
                return ResourceManager.GetString("S3G_Get_Branch_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S3G_SA_Get_BrnDetLst.
        /// </summary>
        public static string S3G_Get_Branch_Details_List {
            get {
                return ResourceManager.GetString("S3G_Get_Branch_Details_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S3G_SA_Get_BrnDet.
        /// </summary>
        public static string S3G_Get_Branch_Details1 {
            get {
                return ResourceManager.GetString("S3G_Get_Branch_Details1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S3G_SA_Get_BrnList.
        /// </summary>
        public static string S3G_Get_Branch_List {
            get {
                return ResourceManager.GetString("S3G_Get_Branch_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S3G_SA_Get_CmpDet.
        /// </summary>
        public static string S3G_Get_Company_Details {
            get {
                return ResourceManager.GetString("S3G_Get_Company_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S3G_SA_Get_CmpCode.
        /// </summary>
        public static string S3G_Get_CompanyCode {
            get {
                return ResourceManager.GetString("S3G_Get_CompanyCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S3G_SA_Get_CmpMastLst.
        /// </summary>
        public static string S3G_Get_CompanyMaster_List {
            get {
                return ResourceManager.GetString("S3G_Get_CompanyMaster_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S3G_SA_Get_ConstDetEnqUpd.
        /// </summary>
        public static string S3G_Get_Constitution_Details_Enquiry_Updation {
            get {
                return ResourceManager.GetString("S3G_Get_Constitution_Details_Enquiry_Updation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S3G_SA_Get_CrncyDet.
        /// </summary>
        public static string S3G_Get_Currency_Details {
            get {
                return ResourceManager.GetString("S3G_Get_Currency_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S3G_SA_Get_CrncyDetByCmpID.
        /// </summary>
        public static string S3G_Get_Currency_Details_ByCompanyID {
            get {
                return ResourceManager.GetString("S3G_Get_Currency_Details_ByCompanyID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S3G_SA_Get_CrncyDetEnqUpd.
        /// </summary>
        public static string S3G_Get_Currency_Details_Enquiry_Updation {
            get {
                return ResourceManager.GetString("S3G_Get_Currency_Details_Enquiry_Updation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S3G_SA_Get_CrncyDetPagi.
        /// </summary>
        public static string S3G_Get_Currency_Details_Paging {
            get {
                return ResourceManager.GetString("S3G_Get_Currency_Details_Paging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S3G_SA_Get_CrncyLstNew.
        /// </summary>
        public static string S3G_Get_Currency_LIST {
            get {
                return ResourceManager.GetString("S3G_Get_Currency_LIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S3G_SA_Get_CustCode.
        /// </summary>
        public static string S3G_Get_Customer_Code {
            get {
                return ResourceManager.GetString("S3G_Get_Customer_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S3G_SA_Get_CustCodeCGT.
        /// </summary>
        public static string S3G_Get_Customer_Code_CGT {
            get {
                return ResourceManager.GetString("S3G_Get_Customer_Code_CGT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S3G_SA_Get_CustCodeCPA.
        /// </summary>
        public static string S3G_Get_Customer_Code_CPA {
            get {
                return ResourceManager.GetString("S3G_Get_Customer_Code_CPA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S3G_SA_Get_CustCodeCPT.
        /// </summary>
        public static string S3G_Get_Customer_Code_CPT {
            get {
                return ResourceManager.GetString("S3G_Get_Customer_Code_CPT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S3G_SA_Get_CustDetEnqUpd.
        /// </summary>
        public static string S3G_Get_Customer_Details_Enquiry_Updation {
            get {
                return ResourceManager.GetString("S3G_Get_Customer_Details_Enquiry_Updation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S3G_SA_Get_CustAlert.
        /// </summary>
        public static string S3G_Get_CustomerAlert {
            get {
                return ResourceManager.GetString("S3G_Get_CustomerAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S3G_SA_Get_CustAlertPagi.
        /// </summary>
        public static string S3G_Get_CustomerAlert_Paging {
            get {
                return ResourceManager.GetString("S3G_Get_CustomerAlert_Paging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S3G_SA_Get_DNCDet.
        /// </summary>
        public static string S3G_Get_DNCDetails {
            get {
                return ResourceManager.GetString("S3G_Get_DNCDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S3G_SA_Get_DNCDetView.
        /// </summary>
        public static string S3G_Get_DNCDetails_view {
            get {
                return ResourceManager.GetString("S3G_Get_DNCDetails_view", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S3G_SA_Get_DocFlagList.
        /// </summary>
        public static string S3G_Get_DocumentationFlag_List {
            get {
                return ResourceManager.GetString("S3G_Get_DocumentationFlag_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S3G_SA_Get_DocPathDet.
        /// </summary>
        public static string S3G_Get_DocumentationPath_Details {
            get {
                return ResourceManager.GetString("S3G_Get_DocumentationPath_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S3G_SA_Get_DocPathPagi.
        /// </summary>
        public static string S3G_Get_DocumentationPath_Paging {
            get {
                return ResourceManager.GetString("S3G_Get_DocumentationPath_Paging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S3G_SA_Get_DocTypeLst.
        /// </summary>
        public static string S3G_Get_DocumentType_List {
            get {
                return ResourceManager.GetString("S3G_Get_DocumentType_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S3G_SA_Get_EnqNo.
        /// </summary>
        public static string S3G_Get_Enquiry_No {
            get {
                return ResourceManager.GetString("S3G_Get_Enquiry_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S3G_SA_Get_EnqNoCPA.
        /// </summary>
        public static string S3G_Get_Enquiry_No_CPA {
            get {
                return ResourceManager.GetString("S3G_Get_Enquiry_No_CPA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S3G_SA_Get_EnqNoCPT.
        /// </summary>
        public static string S3G_Get_Enquiry_No_CPT {
            get {
                return ResourceManager.GetString("S3G_Get_Enquiry_No_CPT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S3G_SA_Get_EnqNoCGT.
        /// </summary>
        public static string S3G_Get_EnquiryNo_CGT {
            get {
                return ResourceManager.GetString("S3G_Get_EnquiryNo_CGT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S3G_SA_Get_EntyType.
        /// </summary>
        public static string S3G_Get_EntityType {
            get {
                return ResourceManager.GetString("S3G_Get_EntityType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S3G_SA_Get_EsclnPagi.
        /// </summary>
        public static string S3G_Get_Escalation_Paging {
            get {
                return ResourceManager.GetString("S3G_Get_Escalation_Paging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S3G_SA_Get_EsclnDet.
        /// </summary>
        public static string S3G_Get_EscalationDetails {
            get {
                return ResourceManager.GetString("S3G_Get_EscalationDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S3G_SA_Get_EventType.
        /// </summary>
        public static string S3G_Get_EventType {
            get {
                return ResourceManager.GetString("S3G_Get_EventType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S3G_SA_Get_ExRateDefaultDet.
        /// </summary>
        public static string S3G_Get_ExchangeRate_Default_Details {
            get {
                return ResourceManager.GetString("S3G_Get_ExchangeRate_Default_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S3G_SA_Get_ExRateDet.
        /// </summary>
        public static string S3G_Get_ExchangeRate_Details {
            get {
                return ResourceManager.GetString("S3G_Get_ExchangeRate_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S3G_SA_Get_ExRatePagi.
        /// </summary>
        public static string S3G_Get_ExchangeRate_Paging {
            get {
                return ResourceManager.GetString("S3G_Get_ExchangeRate_Paging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S3G_SA_Get_ExstCustDetEnqUpd.
        /// </summary>
        public static string S3G_Get_Exist_Customer_Details_Enquiry_Updation {
            get {
                return ResourceManager.GetString("S3G_Get_Exist_Customer_Details_Enquiry_Updation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S3G_SA_Get_ExstCustDetRcptProc.
        /// </summary>
        public static string S3G_Get_Exist_Customer_Details_ReceiptProcessing {
            get {
                return ResourceManager.GetString("S3G_Get_Exist_Customer_Details_ReceiptProcessing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S3G_SA_Get_GLCodeLst.
        /// </summary>
        public static string S3G_Get_GLCode_LIST {
            get {
                return ResourceManager.GetString("S3G_Get_GLCode_LIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S3G_SA_Get_GPSDet.
        /// </summary>
        public static string S3G_Get_GlobalParam_Details {
            get {
                return ResourceManager.GetString("S3G_Get_GlobalParam_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S3G_SA_Get_GPSDetEnqUpd.
        /// </summary>
        public static string S3G_Get_GlobalParam_Details_Enquiry_Updation {
            get {
                return ResourceManager.GetString("S3G_Get_GlobalParam_Details_Enquiry_Updation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S3G_SA_Get_GPSDetnew.
        /// </summary>
        public static string S3G_Get_GlobalParam_Details_new {
            get {
                return ResourceManager.GetString("S3G_Get_GlobalParam_Details_new", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S3G_SA_Get_GPSDetDC.
        /// </summary>
        public static string S3G_Get_GlobalParamDetails_DebtCollector {
            get {
                return ResourceManager.GetString("S3G_Get_GlobalParamDetails_DebtCollector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S3G_SA_Get_GblCmpDet.
        /// </summary>
        public static string S3G_Get_GobalCompanyDetails {
            get {
                return ResourceManager.GetString("S3G_Get_GobalCompanyDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S3G_SA_Get_LOBDet.
        /// </summary>
        public static string S3G_Get_LOB_Details {
            get {
                return ResourceManager.GetString("S3G_Get_LOB_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S3G_SA_Get_LOBDistinLst.
        /// </summary>
        public static string S3G_Get_LOB_DISTINCTLIST {
            get {
                return ResourceManager.GetString("S3G_Get_LOB_DISTINCTLIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S3G_SA_Get_LOBLst.
        /// </summary>
        public static string S3G_Get_LOB_LIST {
            get {
                return ResourceManager.GetString("S3G_Get_LOB_LIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S3G_SA_Get_LOBLstNew.
        /// </summary>
        public static string S3G_Get_LOB_LISTNew {
            get {
                return ResourceManager.GetString("S3G_Get_LOB_LISTNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S3G_SA_Get_LOBPagi.
        /// </summary>
        public static string S3G_Get_LOB_Paging {
            get {
                return ResourceManager.GetString("S3G_Get_LOB_Paging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S3G_SA_Get_LOBProdConstDet.
        /// </summary>
        public static string S3G_Get_LOB_Product_Constitution_Details {
            get {
                return ResourceManager.GetString("S3G_Get_LOB_Product_Constitution_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S3G_SA_Get_LookupTaxType.
        /// </summary>
        public static string S3G_Get_LookUp_TaxType {
            get {
                return ResourceManager.GetString("S3G_Get_LookUp_TaxType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S3G_SA_Get_ModMastDet.
        /// </summary>
        public static string S3G_Get_ModuleMaster_Details {
            get {
                return ResourceManager.GetString("S3G_Get_ModuleMaster_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S3G_SA_Get_ModMastLst.
        /// </summary>
        public static string S3G_Get_ModuleMaster_List {
            get {
                return ResourceManager.GetString("S3G_Get_ModuleMaster_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S3G_SA_Get_ModMastLst1.
        /// </summary>
        public static string S3G_Get_ModuleMaster_List1 {
            get {
                return ResourceManager.GetString("S3G_Get_ModuleMaster_List1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S3G_SA_Get_ProdDet.
        /// </summary>
        public static string S3G_Get_Product_Details {
            get {
                return ResourceManager.GetString("S3G_Get_Product_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S3G_SA_Get_ProdLst.
        /// </summary>
        public static string S3G_Get_Product_List {
            get {
                return ResourceManager.GetString("S3G_Get_Product_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S3G_SA_Get_ProdPagi.
        /// </summary>
        public static string S3G_Get_Product_Paging {
            get {
                return ResourceManager.GetString("S3G_Get_Product_Paging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S3G_SA_Get_PgmMastDet.
        /// </summary>
        public static string S3G_Get_ProgramMaster_Details {
            get {
                return ResourceManager.GetString("S3G_Get_ProgramMaster_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S3G_SA_Get_PgmMastLst.
        /// </summary>
        public static string S3G_Get_ProgramMaster_List {
            get {
                return ResourceManager.GetString("S3G_Get_ProgramMaster_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S3G_SA_Get_PgmMastLst1.
        /// </summary>
        public static string S3G_Get_ProgramMaster_List1 {
            get {
                return ResourceManager.GetString("S3G_Get_ProgramMaster_List1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S3G_SA_Get_PgmMastForORGDet.
        /// </summary>
        public static string S3G_Get_ProgramMasterForORG_Details {
            get {
                return ResourceManager.GetString("S3G_Get_ProgramMasterForORG_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S3G_SA_Get_PgmWFPgmMap.
        /// </summary>
        public static string S3G_Get_ProgramWFPrgMapping {
            get {
                return ResourceManager.GetString("S3G_Get_ProgramWFPrgMapping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S3G_SA_Get_RegnCode.
        /// </summary>
        public static string S3G_Get_Region_Code {
            get {
                return ResourceManager.GetString("S3G_Get_Region_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S3G_SA_Get_RegnCodeForUTPA.
        /// </summary>
        public static string S3G_Get_Region_CodeForUTPA {
            get {
                return ResourceManager.GetString("S3G_Get_Region_CodeForUTPA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S3G_SA_Get_RegnDet.
        /// </summary>
        public static string S3G_Get_Region_Details {
            get {
                return ResourceManager.GetString("S3G_Get_Region_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S3G_SA_Get_RegnDetView.
        /// </summary>
        public static string S3G_Get_Region_Details_View {
            get {
                return ResourceManager.GetString("S3G_Get_Region_Details_View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S3G_SA_Get_RegnDet.
        /// </summary>
        public static string S3G_Get_Region_Details1 {
            get {
                return ResourceManager.GetString("S3G_Get_Region_Details1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S3G_SA_Get_RegnName.
        /// </summary>
        public static string S3G_Get_Region_Name {
            get {
                return ResourceManager.GetString("S3G_Get_Region_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S3G_SA_Get_RoleCenLst.
        /// </summary>
        public static string S3G_Get_RoleCenterCode_List {
            get {
                return ResourceManager.GetString("S3G_Get_RoleCenterCode_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S3G_SA_Get_RoleCenMastLst.
        /// </summary>
        public static string S3G_Get_RoleCenterMaster_List {
            get {
                return ResourceManager.GetString("S3G_Get_RoleCenterMaster_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S3G_SA_Get_RoleCodeLst.
        /// </summary>
        public static string S3G_Get_RoleCode_List {
            get {
                return ResourceManager.GetString("S3G_Get_RoleCode_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S3G_SA_Get_RoleCodeMastDet.
        /// </summary>
        public static string S3G_Get_RoleCodeMaster_Details {
            get {
                return ResourceManager.GetString("S3G_Get_RoleCodeMaster_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S3G_SA_Get_RoleCodeMastPagi.
        /// </summary>
        public static string S3G_Get_RoleCodeMaster_Paging {
            get {
                return ResourceManager.GetString("S3G_Get_RoleCodeMaster_Paging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S3G_SA_Get_RoleUsrLst.
        /// </summary>
        public static string S3G_Get_RoleUser_List {
            get {
                return ResourceManager.GetString("S3G_Get_RoleUser_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S3G_SA_Get_TaxGuidAstDet.
        /// </summary>
        public static string S3G_Get_Taxguide_Asset_Details {
            get {
                return ResourceManager.GetString("S3G_Get_Taxguide_Asset_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S3G_SA_Get_TaxguidDet.
        /// </summary>
        public static string S3G_Get_Taxguide_Details {
            get {
                return ResourceManager.GetString("S3G_Get_Taxguide_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S3G_SA_Get_TaxGuidPagi.
        /// </summary>
        public static string S3G_Get_TaxGuide_Paging {
            get {
                return ResourceManager.GetString("S3G_Get_TaxGuide_Paging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S3G_SA_Get_TmpRcptBookNo.
        /// </summary>
        public static string S3G_Get_Temp_Receipt_BookNo {
            get {
                return ResourceManager.GetString("S3G_Get_Temp_Receipt_BookNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S3G_SA_Get_UsrDet.
        /// </summary>
        public static string S3G_Get_User_Details {
            get {
                return ResourceManager.GetString("S3G_Get_User_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S3G_SA_Get_UsrDetPagi.
        /// </summary>
        public static string S3G_Get_User_Details_Paging {
            get {
                return ResourceManager.GetString("S3G_Get_User_Details_Paging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S3G_SA_Get_UsrPagi.
        /// </summary>
        public static string S3G_Get_User_Paging {
            get {
                return ResourceManager.GetString("S3G_Get_User_Paging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S3G_SA_Get_UsrBrnDet.
        /// </summary>
        public static string S3G_Get_UserBranch_Details {
            get {
                return ResourceManager.GetString("S3G_Get_UserBranch_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S3G_SA_Get_UsrBrnRoleDet.
        /// </summary>
        public static string S3G_Get_UserBranchRole_Details {
            get {
                return ResourceManager.GetString("S3G_Get_UserBranchRole_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S3G_SA_Get_UsrCodeDet.
        /// </summary>
        public static string S3G_Get_UserCode_Details {
            get {
                return ResourceManager.GetString("S3G_Get_UserCode_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S3G_SA_Get_UsrLOBMap.
        /// </summary>
        public static string S3G_Get_UserLOBMapping {
            get {
                return ResourceManager.GetString("S3G_Get_UserLOBMapping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S3G_SA_Get_UsrMnuItems.
        /// </summary>
        public static string S3G_Get_UserMenuItems {
            get {
                return ResourceManager.GetString("S3G_Get_UserMenuItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S3G_SA_Get_UsrMnuItemsNew.
        /// </summary>
        public static string S3G_Get_UserMenuItemsNew {
            get {
                return ResourceManager.GetString("S3G_Get_UserMenuItemsNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S3G_SA_Get_UsrRoleDet.
        /// </summary>
        public static string S3G_Get_UserRole_Details {
            get {
                return ResourceManager.GetString("S3G_Get_UserRole_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S3G_SA_Get_UTPABrnLst.
        /// </summary>
        public static string S3G_Get_UTPA_Branch_List {
            get {
                return ResourceManager.GetString("S3G_Get_UTPA_Branch_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S3G_SA_Get_UTPACustMast.
        /// </summary>
        public static string S3G_Get_UTPA_CustomerMaster {
            get {
                return ResourceManager.GetString("S3G_Get_UTPA_CustomerMaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S3G_SA_Get_UTPACustName.
        /// </summary>
        public static string S3G_Get_UTPA_CustomerName {
            get {
                return ResourceManager.GetString("S3G_Get_UTPA_CustomerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S3G_SA_Get_UTPADet.
        /// </summary>
        public static string S3G_Get_UTPA_Details {
            get {
                return ResourceManager.GetString("S3G_Get_UTPA_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S3G_SA_Get_UTPALOBLIST.
        /// </summary>
        public static string S3G_Get_UTPA_LOB_LIST {
            get {
                return ResourceManager.GetString("S3G_Get_UTPA_LOB_LIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S3G_SA_Get_UTPAPagi.
        /// </summary>
        public static string S3G_Get_UTPA_Paging {
            get {
                return ResourceManager.GetString("S3G_Get_UTPA_Paging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S3G_SA_Get_UTPATypeMast.
        /// </summary>
        public static string S3G_Get_UTPA_TypeMaster {
            get {
                return ResourceManager.GetString("S3G_Get_UTPA_TypeMaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S3G_SA_Get_UTPAPgmAccsDet.
        /// </summary>
        public static string S3G_Get_UTPAProgramAccess_Details {
            get {
                return ResourceManager.GetString("S3G_Get_UTPAProgramAccess_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S3G_SA_Get_BatchLst.
        /// </summary>
        public static string S3G_GetBatch_List {
            get {
                return ResourceManager.GetString("S3G_GetBatch_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S3G_SA_Get_ConstCateg.
        /// </summary>
        public static string S3G_GetCons_Category {
            get {
                return ResourceManager.GetString("S3G_GetCons_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S3G_SA_Get_CustDet.
        /// </summary>
        public static string S3G_GetCustomerDetails {
            get {
                return ResourceManager.GetString("S3G_GetCustomerDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S3G_SA_Get_CustAcc.
        /// </summary>
        public static string S3G_GetCustomersAccount {
            get {
                return ResourceManager.GetString("S3G_GetCustomersAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S3G_SA_Get_EnqNoStatus.
        /// </summary>
        public static string S3g_GetEnquiryNumberStatus {
            get {
                return ResourceManager.GetString("S3g_GetEnquiryNumberStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S3G_SA_Get_PgmRefnoDet.
        /// </summary>
        public static string S3G_GetProgramrefno_Details {
            get {
                return ResourceManager.GetString("S3G_GetProgramrefno_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S3G_SA_Get_UsrBrnMap.
        /// </summary>
        public static string S3G_GetUserBranchMapping {
            get {
                return ResourceManager.GetString("S3G_GetUserBranchMapping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S3G_SA_Get_UsrLobMap.
        /// </summary>
        public static string S3G_GetUserLobMapping {
            get {
                return ResourceManager.GetString("S3G_GetUserLobMapping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S3G_SA_Ins_AccSetup.
        /// </summary>
        public static string S3G_Insert_AccountSetup {
            get {
                return ResourceManager.GetString("S3G_Insert_AccountSetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S3G_SA_Ins_AstDesc.
        /// </summary>
        public static string S3G_Insert_Asset_Desc {
            get {
                return ResourceManager.GetString("S3G_Insert_Asset_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S3G_SA_Ins_BnkStmtCapt.
        /// </summary>
        public static string S3G_Insert_BankStatement_Capture {
            get {
                return ResourceManager.GetString("S3G_Insert_BankStatement_Capture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S3G_SA_Ins_BnkStmtDataCapt.
        /// </summary>
        public static string S3G_Insert_BankStatement_DataCapture {
            get {
                return ResourceManager.GetString("S3G_Insert_BankStatement_DataCapture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S3G_SA_Ins_BnkStmtLOVDet.
        /// </summary>
        public static string S3G_Insert_BankStatement_LOVDetails {
            get {
                return ResourceManager.GetString("S3G_Insert_BankStatement_LOVDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S3G_SA_Ins_BrnDet.
        /// </summary>
        public static string S3G_Insert_Branch_Details {
            get {
                return ResourceManager.GetString("S3G_Insert_Branch_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S3G_SA_Ins_CmpDet.
        /// </summary>
        public static string S3G_Insert_Company_Details {
            get {
                return ResourceManager.GetString("S3G_Insert_Company_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S3G_SA_Ins_CrncyDet.
        /// </summary>
        public static string S3G_Insert_Currency_Details {
            get {
                return ResourceManager.GetString("S3G_Insert_Currency_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S3G_SA_Ins_CustAlert.
        /// </summary>
        public static string S3G_Insert_CustomerAlert {
            get {
                return ResourceManager.GetString("S3G_Insert_CustomerAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S3G_SA_Ins_DocPathDet.
        /// </summary>
        public static string S3G_Insert_DocPath_Details {
            get {
                return ResourceManager.GetString("S3G_Insert_DocPath_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S3G_SA_Ins_EsclnDet.
        /// </summary>
        public static string S3G_Insert_EscalationDetails {
            get {
                return ResourceManager.GetString("S3G_Insert_EscalationDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S3G_SA_Ins_ExRateDet.
        /// </summary>
        public static string S3G_Insert_ExchangeRate_Details {
            get {
                return ResourceManager.GetString("S3G_Insert_ExchangeRate_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S3G_SA_Ins_FldInfReport.
        /// </summary>
        public static string S3G_Insert_FieldInformationReport {
            get {
                return ResourceManager.GetString("S3G_Insert_FieldInformationReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S3G_SA_Ins_GPSDet.
        /// </summary>
        public static string S3G_Insert_GlobalParam_Details {
            get {
                return ResourceManager.GetString("S3G_Insert_GlobalParam_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S3G_SA_Ins_GPSMonEndDet.
        /// </summary>
        public static string S3G_Insert_GlobalParamMonthEnd_Details {
            get {
                return ResourceManager.GetString("S3G_Insert_GlobalParamMonthEnd_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S3G_SA_Ins_LOBDet.
        /// </summary>
        public static string S3G_Insert_LOB_Details {
            get {
                return ResourceManager.GetString("S3G_Insert_LOB_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S3G_SA_Ins_ProdDet.
        /// </summary>
        public static string S3G_Insert_Product_Details {
            get {
                return ResourceManager.GetString("S3G_Insert_Product_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S3G_SA_Ins_RegnDet.
        /// </summary>
        public static string S3G_Insert_Region_Details {
            get {
                return ResourceManager.GetString("S3G_Insert_Region_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S3G_SA_Ins_RoleCodeMastDet.
        /// </summary>
        public static string S3G_Insert_RoleCodeMaster_Details {
            get {
                return ResourceManager.GetString("S3G_Insert_RoleCodeMaster_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S3G_SA_Ins_TaxGuidDet.
        /// </summary>
        public static string S3G_Insert_TaxGuide_Details {
            get {
                return ResourceManager.GetString("S3G_Insert_TaxGuide_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S3G_SA_Ins_UsrDet.
        /// </summary>
        public static string S3G_Insert_User_Details {
            get {
                return ResourceManager.GetString("S3G_Insert_User_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S3G_SA_Ins_UTPADet.
        /// </summary>
        public static string S3G_Insert_UTPA_Details {
            get {
                return ResourceManager.GetString("S3G_Insert_UTPA_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S3G_SA_Ins_UTPAPgmAccsDet.
        /// </summary>
        public static string S3G_Insert_UTPAProgramAccess_Details {
            get {
                return ResourceManager.GetString("S3G_Insert_UTPAProgramAccess_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S3G_SA_Ins_DNCDet.
        /// </summary>
        public static string S3G_InsertDNCDetails {
            get {
                return ResourceManager.GetString("S3G_InsertDNCDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S3G_LA_Get_LOBBrnMonEndParam.
        /// </summary>
        public static string S3G_LOANAD_GetLOB_BranchMonthEndParam {
            get {
                return ResourceManager.GetString("S3G_LOANAD_GetLOB_BranchMonthEndParam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S3G_OR_Get_DocCtrlNo.
        /// </summary>
        public static string S3G_ORG_GetDocumentControlNo {
            get {
                return ResourceManager.GetString("S3G_ORG_GetDocumentControlNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S3G_OR_Get_PgmMast.
        /// </summary>
        public static string S3G_ORG_GetWorkflowProgramMaster {
            get {
                return ResourceManager.GetString("S3G_ORG_GetWorkflowProgramMaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S3G_SA_Get_CrncyLst.
        /// </summary>
        public static string S3G_SYS_Get_Currency_List {
            get {
                return ResourceManager.GetString("S3G_SYS_Get_Currency_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S3G_SA_Get_ExstLocMap.
        /// </summary>
        public static string S3G_SYSAD_ExistLocationMapping {
            get {
                return ResourceManager.GetString("S3G_SYSAD_ExistLocationMapping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S3G_SA_Get_UsrDetNew.
        /// </summary>
        public static string S3G_SYSAD_Get_User_Details {
            get {
                return ResourceManager.GetString("S3G_SYSAD_Get_User_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S3G_SA_Get_UsrDetPagiNew.
        /// </summary>
        public static string S3G_SYSAD_Get_User_Details_Paging {
            get {
                return ResourceManager.GetString("S3G_SYSAD_Get_User_Details_Paging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S3G_SA_Get_UsrRoleLocDtls.
        /// </summary>
        public static string S3G_SYSAD_Get_User_RoleLocationDtls {
            get {
                return ResourceManager.GetString("S3G_SYSAD_Get_User_RoleLocationDtls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S3G_SA_Get_UsrBrnRoleDetNew.
        /// </summary>
        public static string S3G_SYSAD_Get_UserBranchRole_Details {
            get {
                return ResourceManager.GetString("S3G_SYSAD_Get_UserBranchRole_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S3G_SA_Get_UsrCodeDetNew.
        /// </summary>
        public static string S3G_SYSAD_Get_UserCode_Details {
            get {
                return ResourceManager.GetString("S3G_SYSAD_Get_UserCode_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S3G_SA_Get_UsrLocDet.
        /// </summary>
        public static string S3G_SYSAD_Get_UserLocation_Details {
            get {
                return ResourceManager.GetString("S3G_SYSAD_Get_UserLocation_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S3G_SA_Get_UsrRoleDet.
        /// </summary>
        public static string S3G_SYSAD_Get_UserRole_Details {
            get {
                return ResourceManager.GetString("S3G_SYSAD_Get_UserRole_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S3G_SA_Get_AddrLoodup.
        /// </summary>
        public static string S3G_SYSAD_GetAddressLoodup {
            get {
                return ResourceManager.GetString("S3G_SYSAD_GetAddressLoodup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S3G_SA_Get_AllLocCateg.
        /// </summary>
        public static string S3G_SYSAD_GetAllLocationCategory {
            get {
                return ResourceManager.GetString("S3G_SYSAD_GetAllLocationCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S3G_SA_Get_AstCategLst.
        /// </summary>
        public static string S3G_SysAd_GetAssetCategory_List {
            get {
                return ResourceManager.GetString("S3G_SysAd_GetAssetCategory_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S3G_SA_Get_AudTrialDet.
        /// </summary>
        public static string S3G_SYSAD_GetAuditTrialDetails {
            get {
                return ResourceManager.GetString("S3G_SYSAD_GetAuditTrialDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S3G_SA_Get_AudTrialPagi.
        /// </summary>
        public static string S3G_SYSAD_GetAuditTrialPaging {
            get {
                return ResourceManager.GetString("S3G_SYSAD_GetAuditTrialPaging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S3G_SA_Get_GblMLASLA.
        /// </summary>
        public static string S3G_SYSAD_GetGlobalMLASLA {
            get {
                return ResourceManager.GetString("S3G_SYSAD_GetGlobalMLASLA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S3G_SA_Get_GPS.
        /// </summary>
        public static string S3G_SYSAD_GetGlobalParameters {
            get {
                return ResourceManager.GetString("S3G_SYSAD_GetGlobalParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S3G_SA_Get_HierachyMastDet.
        /// </summary>
        public static string S3G_SYSAD_GetHierachyMasterDetails {
            get {
                return ResourceManager.GetString("S3G_SYSAD_GetHierachyMasterDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S3G_SA_Get_LocCategDet.
        /// </summary>
        public static string S3G_SYSAD_GetLocationCategoryDetails {
            get {
                return ResourceManager.GetString("S3G_SYSAD_GetLocationCategoryDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S3G_SA_Get_LocCategDetPagi.
        /// </summary>
        public static string S3G_SYSAD_GetLocationCategoryDetails_Paging {
            get {
                return ResourceManager.GetString("S3G_SYSAD_GetLocationCategoryDetails_Paging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S3G_SA_Get_LocMapDet.
        /// </summary>
        public static string S3G_SYSAD_GetLocationMappingDetails {
            get {
                return ResourceManager.GetString("S3G_SYSAD_GetLocationMappingDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S3G_SA_Get_LocMapDetPagi.
        /// </summary>
        public static string S3G_SYSAD_GetLocationMappingDetails_Paging {
            get {
                return ResourceManager.GetString("S3G_SYSAD_GetLocationMappingDetails_Paging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S3G_SA_Get_LocTreeView.
        /// </summary>
        public static string S3G_SYSAD_GETLOCATIONTREEVIEW {
            get {
                return ResourceManager.GetString("S3G_SYSAD_GETLOCATIONTREEVIEW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S3G_SA_Get_PgmCode.
        /// </summary>
        public static string S3G_SYSAD_GetProgramCode {
            get {
                return ResourceManager.GetString("S3G_SYSAD_GetProgramCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S3G_SA_Get_WFPgmByPgmId.
        /// </summary>
        public static string S3G_SYSAD_GetWFProgramsByProgramId {
            get {
                return ResourceManager.GetString("S3G_SYSAD_GetWFProgramsByProgramId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S3G_SA_Ins_UsrDetNew.
        /// </summary>
        public static string S3G_SYSAD_Insert_UserDetails {
            get {
                return ResourceManager.GetString("S3G_SYSAD_Insert_UserDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S3G_SA_Ins_AudQuery.
        /// </summary>
        public static string S3G_SYSAD_InsertAuditQuery {
            get {
                return ResourceManager.GetString("S3G_SYSAD_InsertAuditQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S3G_SA_Ins_AudTrial.
        /// </summary>
        public static string S3G_SYSAD_InsertAuditTrial {
            get {
                return ResourceManager.GetString("S3G_SYSAD_InsertAuditTrial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S3G_SA_Ins_HierarchyMast.
        /// </summary>
        public static string S3G_SYSAD_InsertHierachyMaster {
            get {
                return ResourceManager.GetString("S3G_SYSAD_InsertHierachyMaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S3G_SA_Ins_LocCateg.
        /// </summary>
        public static string S3G_SYSAD_InsertLocationCategory {
            get {
                return ResourceManager.GetString("S3G_SYSAD_InsertLocationCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S3G_SA_Ins_LocMast.
        /// </summary>
        public static string S3G_SYSAD_InsertLocationMaster {
            get {
                return ResourceManager.GetString("S3G_SYSAD_InsertLocationMaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S3G_SA_Upd_GblLobBrnLock.
        /// </summary>
        public static string S3G_SysAd_UpdateGlobalLobBranchLock {
            get {
                return ResourceManager.GetString("S3G_SysAd_UpdateGlobalLobBranchLock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S3G_SA_Upd_LocCateg.
        /// </summary>
        public static string S3G_SYSAD_UpdateLocationCategory {
            get {
                return ResourceManager.GetString("S3G_SYSAD_UpdateLocationCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S3G_SA_Upd_LocMap.
        /// </summary>
        public static string S3G_SYSAD_UpdateLocationMapping {
            get {
                return ResourceManager.GetString("S3G_SYSAD_UpdateLocationMapping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S3G_SA_Get_LoginUsrPwd.
        /// </summary>
        public static string S3G_SYSADM_GetLoginUserPassword {
            get {
                return ResourceManager.GetString("S3G_SYSADM_GetLoginUserPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S3G_SA_Upd_AccSetup.
        /// </summary>
        public static string S3G_Update_AccountSetup {
            get {
                return ResourceManager.GetString("S3G_Update_AccountSetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S3G_SA_Upd_BnkStmtDataCapt.
        /// </summary>
        public static string S3G_Update_BankStatement_DataCapture {
            get {
                return ResourceManager.GetString("S3G_Update_BankStatement_DataCapture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S3G_SA_Upd_BrnDet.
        /// </summary>
        public static string S3G_Update_Branch_Details {
            get {
                return ResourceManager.GetString("S3G_Update_Branch_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S3G_SA_Upd_CmpDet.
        /// </summary>
        public static string S3G_Update_Company_Details {
            get {
                return ResourceManager.GetString("S3G_Update_Company_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S3G_SA_Upd_CrncyDet.
        /// </summary>
        public static string S3G_Update_Currency_Details {
            get {
                return ResourceManager.GetString("S3G_Update_Currency_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S3G_SA_Upd_CustAlert.
        /// </summary>
        public static string S3G_Update_CustomerAlert {
            get {
                return ResourceManager.GetString("S3G_Update_CustomerAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S3G_SA_Upd_DNCDet.
        /// </summary>
        public static string S3G_Update_DNC_Details {
            get {
                return ResourceManager.GetString("S3G_Update_DNC_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S3G_SA_Upd_DocPathDet.
        /// </summary>
        public static string S3G_Update_DocPath_Details {
            get {
                return ResourceManager.GetString("S3G_Update_DocPath_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S3G_SA_Upd_EsclnDet.
        /// </summary>
        public static string S3G_Update_EscalationDetails {
            get {
                return ResourceManager.GetString("S3G_Update_EscalationDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S3G_SA_Upd_ExRateDet.
        /// </summary>
        public static string S3G_Update_ExchangeRate_Details {
            get {
                return ResourceManager.GetString("S3G_Update_ExchangeRate_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S3G_SA_Upd_FldInfRptCancel.
        /// </summary>
        public static string S3G_Update_FieldInformationReportCancel {
            get {
                return ResourceManager.GetString("S3G_Update_FieldInformationReportCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S3G_SA_Upd_GPSDet.
        /// </summary>
        public static string S3G_Update_GlobalParam_Details {
            get {
                return ResourceManager.GetString("S3G_Update_GlobalParam_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S3G_SA_Upd_GPSMonEndDet.
        /// </summary>
        public static string S3G_Update_GlobalParamMonthEnd_Details {
            get {
                return ResourceManager.GetString("S3G_Update_GlobalParamMonthEnd_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S3G_SA_Upd_LOBDet.
        /// </summary>
        public static string S3G_Update_LOB_Details {
            get {
                return ResourceManager.GetString("S3G_Update_LOB_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S3G_SA_Upd_LOBMap.
        /// </summary>
        public static string S3G_Update_LOBMapping {
            get {
                return ResourceManager.GetString("S3G_Update_LOBMapping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S3G_SA_Upd_ProdDet.
        /// </summary>
        public static string S3G_Update_Product_Details {
            get {
                return ResourceManager.GetString("S3G_Update_Product_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S3G_SA_Upd_RegnDet.
        /// </summary>
        public static string S3G_Update_Region_Details {
            get {
                return ResourceManager.GetString("S3G_Update_Region_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S3G_SA_Upd_RoleCodeMastDet.
        /// </summary>
        public static string S3G_Update_RoleCodeMaster_Details {
            get {
                return ResourceManager.GetString("S3G_Update_RoleCodeMaster_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S3G_SA_Upd_UsrDet.
        /// </summary>
        public static string S3G_Update_User_Details {
            get {
                return ResourceManager.GetString("S3G_Update_User_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S3G_SA_Upd_UTPADet.
        /// </summary>
        public static string S3G_Update_UTPA_Details {
            get {
                return ResourceManager.GetString("S3G_Update_UTPA_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S3G_SA_Upd_UTPAPgmAccsDet.
        /// </summary>
        public static string S3G_Update_UTPAProgramAccess_Details {
            get {
                return ResourceManager.GetString("S3G_Update_UTPAProgramAccess_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S3G_SA_Val_Login.
        /// </summary>
        public static string S3G_Validate_Login {
            get {
                return ResourceManager.GetString("S3G_Validate_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S3G_SA_Val_LoginNew.
        /// </summary>
        public static string S3G_Validate_Login_new {
            get {
                return ResourceManager.GetString("S3G_Validate_Login_new", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S3G_SA_Val_LoginNewNew.
        /// </summary>
        public static string S3G_Validate_Login_new_New {
            get {
                return ResourceManager.GetString("S3G_Validate_Login_new_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S3G_SA_Val_Login1.
        /// </summary>
        public static string S3G_Validate_Login1 {
            get {
                return ResourceManager.GetString("S3G_Validate_Login1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S3G_WF_Get_FNLastUsdUsrMkrChk.
        /// </summary>
        public static string S3G_WORKFLOW_FNGetLastUsedUser_MakerChk {
            get {
                return ResourceManager.GetString("S3G_WORKFLOW_FNGetLastUsedUser_MakerChk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S3G_WF_Get_FNLastUsdUsrApprCPA.
        /// </summary>
        public static string S3G_WORKFLOW_FNGetLastUsedUserApprovalCPA {
            get {
                return ResourceManager.GetString("S3G_WORKFLOW_FNGetLastUsedUserApprovalCPA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S3G_WF_Get_FNLastUsdUsrLstMChk.
        /// </summary>
        public static string S3G_WORKFLOW_FNGetLastUserInList_MakerChk {
            get {
                return ResourceManager.GetString("S3G_WORKFLOW_FNGetLastUserInList_MakerChk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S3G_WF_Get_FNLastUsdUsrLstApprCPA.
        /// </summary>
        public static string S3G_WORKFLOW_FNGetLastUserInListApprovalCPA {
            get {
                return ResourceManager.GetString("S3G_WORKFLOW_FNGetLastUserInListApprovalCPA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S3G_WF_Get_ApprCntCPA.
        /// </summary>
        public static string S3G_WORKFLOW_GetApprovalCountCPA {
            get {
                return ResourceManager.GetString("S3G_WORKFLOW_GetApprovalCountCPA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S3G_WF_Get_Apprs.
        /// </summary>
        public static string S3G_WORKFLOW_GetApprovals {
            get {
                return ResourceManager.GetString("S3G_WORKFLOW_GetApprovals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S3G_SA_Get_WF_Pagi.
        /// </summary>
        public static string S3G_WORKFLOW_GetWorkflowPaging {
            get {
                return ResourceManager.GetString("S3G_WORKFLOW_GetWorkflowPaging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S3G_WF_Get_WFRecs.
        /// </summary>
        public static string S3G_WORKFLOW_GetWorkFlowRecords {
            get {
                return ResourceManager.GetString("S3G_WORKFLOW_GetWorkFlowRecords", resourceCulture);
            }
        }
    }
}
